# Generated by Django 5.2.1 on 2025-06-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('status', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualProtection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
